#!/bin/sh

case $1 in
	'build')
		echo Building app
		cd fe-angular
		npm install
		cd ..
		mvn clean install;;
	'run')
		echo Starting DB
		cd docker
		sudo docker compose up -d
		sleep 5
		echo Starting Spring
		cd ../be-spring
		gnome-terminal -- sh -c "bash -c \"mvn spring-boot:run -Dspring-boot.run.profiles=dev\""
		echo Starting Angular
		cd ../fe-angular
		gnome-terminal -- sh -c "bash -c \"npm run start\"";;
	'run-jar')
		echo Starting pre-build application
		cd be-spring
		java -jar isregatta-webapp-0.0.1-SNAPSHOT.jar --spring.profiles.active=dev;;
	'docker-stop')
		echo Stopping DB
		cd docker
		sudo docker compose down;;
	'clean')
		./is-regatta docker-stop
		sudo rm -rf docker/mariadb_data_volume
		rm -rf be-spring/dev-tmp
		rm -rf fe-angular/.angular
		rm -rf fe-angular/node
		rm -rf fe-angular/node_modules
		mvn clean;;
	*)
		echo build       - zostavi aplikaciu do stavu na spustenie
		echo run         - spusti zostavenu aplikaciu
		echo run-jar     - spusti jar bez potreby zostavovania aplikacie
		echo docker-stop - zastavi kontajner s aplikaciou
		echo clean       - odtrani vsetky vygenerovane subory;;
esac
