services:
  mariadb:
    image: mariadb:10.6
    container_name: is-regatta
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: is-regatta
    ports:
      - 3306:3306
    volumes:
      - ./mariadb_data_volume:/var/lib/mysql
