version: '3.1'
services:
  mariadb:
    image: mariadb
    container_name: is-regatta
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
        - ./mariadb_data_volume:/var/lib/mysql
