openapi: 3.0.0
info:
  title: IS Regatta Base REST API
  description: REST API for base and support functions
  version: 0.0.1

servers:
  - url: '{server}/api'
    variables:
      server:
        default: 'http://localhost:8080'

paths:
  /table-data-service/{serviceName}:
    get:
      tags:
        - table-data-service-controller
      summary: Get data for table by service name
      operationId: getTableDataByServiceName
      parameters:
        - name: serviceName
          in: path
          required: true
          description: Table srvice name
          schema:
            type: string
        - name: tableDataRequestDto
          in: query
          required: true
          description: Parameters for required data
          schema:
            $ref: '#/components/schemas/TableDataRequestDto'
      responses:
        200:
          description: Data successfully retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TableDataResponseDto'
        400:
          description: Bad request
        401:
          description: Unauthorized
        403:
          description: Forbidden
        500:
          description: Internal server error

components:
  schemas:
    TableDataRequestDto:
      properties:
        pageSize:
          type: integer
          format: int32
        pageNumber:
          type: integer
          format: int32
        sortCriteria:
          $ref: '#/components/schemas/SortDto'
        filterCriteria:
          type: array
          items:
            $ref: '#/components/schemas/FilterDto'
    SortDto:
      properties:
        column:
          type: string
        direction:
          type: string
    FilterDto:
      properties:
        column:
          type: string
        value:
          type: string
    TableDataResponseDto:
      properties:
        data:
          type: array
          items:
            type: object
        total:
          type: integer
          format: int64