openapi: 3.0.0
info:
  title: IS Regatta Race REST API
  description: REST API for Race management
  version: 0.0.1

servers:
  - url: '{server}/api'
    variables:
      server:
        default: 'http://localhost:8080'

paths:
  /races:
    post:
      tags:
        - race-controller
      summary: Create new race
      operationId: createRace
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUpdateRaceDto'
      responses:
        201:
          description: Race successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RaceDetailDto'
        400:
          description: Bad request
        401:
          description: Unauthorized
        403:
          description: Forbidden
        409:
          description: Conflict
        500:
          description: Internal server error
  /races/race/{raceId}:
    get:
      tags:
        - race-controller
      summary: Get race's info
      operationId: getRace
      parameters:
        - name: raceId
          in: path
          required: true
          description: Race's ID
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: Race's info retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RaceDetailDto'
        400:
          description: Bad request
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Race not found
        500:
          description: Internal server error
    patch:
      tags:
        - race-controller
      summary: Update race's info
      operationId: updateRace
      parameters:
        - name: raceId
          in: path
          required: true
          description: Race's ID
          schema:
            type: integer
            format: int32
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUpdateRaceDto'
      responses:
        200:
          description: Race's info updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RaceDetailDto'
        400:
          description: Bad request
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Race not found
        409:
          description: Conflict
        500:
          description: Internal server error
  /races/race/{raceId}/sign-up:
    post:
      tags:
        - race-controller
      summary: Sign up active user to the race
      operationId: signUpActive
      parameters:
        - name: raceId
          in: path
          required: true
          description: Race's ID
          schema:
            type: integer
            format: int32
      responses:
        201:
          description: Successfully signed up
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RaceUserInfoDto'
        400:
          description: Bad request
        401:
          description: Unauthorized
        403:
          description: Forbidden
        409:
          description: Conflict
        500:
          description: Internal server error
    get:
      tags:
        - race-controller
      summary: Get info if the active user is signed up
      operationId: isSignedUp
      parameters:
        - name: raceId
          in: path
          required: true
          description: Race's ID
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: User's race's info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RaceUserInfoDto'
        400:
          description: Bad request
        401:
          description: Unauthorized
        403:
          description: Forbidden
        409:
          description: Conflict
        500:
          description: Internal server error

components:
  schemas:
    CreateUpdateRaceDto:
      properties:
        name:
          type: string
        location:
          type: string
        date:
          type: string
          format: date
        signUpUntil:
          type: string
          format: date
        description:
          type: string
        isPublic:
          type: boolean
    RaceDetailDto:
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        location:
          type: string
        date:
          type: string
          format: date
        signUpUntil:
          type: string
          format: date
        description:
          type: string
        isPublic:
          type: boolean
        mainOrganizerId:
          type: integer
          format: int32
    RaceDetailListDto:
      properties:
        races:
          type: array
          items:
            $ref: '#/components/schemas/RaceDetailDto'
    UpdateRaceDatesDto:
      properties:
        date:
          type: string
          format: date
        signUpUntil:
          type: string
          format: date
    RaceUserInfoDto:
      properties:
        raceId:
          type: integer
          format: int32
        userId:
          type: integer
          format: int32
        status:
          $ref: '#/components/schemas/RaceUserStatusEnum'
    RaceUserStatusEnum:
      type: string
      enum:
        - APPLIED
        - SIGNED_UP
