openapi: 3.0.0
info:
  title: IS Regatta Race REST API
  description: REST API for Race management
  version: 0.0.1

servers:
  - url: '{server}/api'
    variables:
      server:
        default: 'http://localhost:8080'

paths:
  /races:
    get:
      tags:
        - race-controller
      summary: Get all races
      operationId: getAllRaces
      responses:
        200:
          description: Races successfully retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RaceDetailListDto'
        400:
          description: Bad request
        401:
          description: Unauthorized
        403:
          description: Forbidden
        500:
          description: Internal server error
    post:
      tags:
        - race-controller
      summary: Create new race
      operationId: createRace
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRaceDto'
      responses:
        201:
          description: Race successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RaceDetailDto'
        400:
          description: Bad request
        401:
          description: Unauthorized
        403:
          description: Forbidden
        409:
          description: Conflict
        500:
          description: Internal server error
  /races/{raceId}:
    get:
      tags:
        - race-controller
      summary: Get race's info
      operationId: getRace
      parameters:
        - name: raceId
          in: path
          required: true
          description: Race's ID
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: Race's info retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RaceDetailDto'
        400:
          description: Bad request
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Race not found
        500:
          description: Internal server error
    patch:
      tags:
        - race-controller
      summary: Update race's info
      operationId: updateRace
      parameters:
        - name: raceId
          in: path
          required: true
          description: Race's ID
          schema:
            type: integer
            format: int32
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateRaceDto'
      responses:
        200:
          description: Race's info updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RaceDetailDto'
        400:
          description: Bad request
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Race not found
        409:
          description: Conflict
        500:
          description: Internal server error

components:
  schemas:
    CreateRaceDto:
      properties:
        name:
          type: string
        date:
          type: string
          format: date
    UpdateRaceDto:
      properties:
        name:
          type: string
        location:
          type: string
        date:
          type: string
          format: date
        description:
          type: string
        isPublic:
          type: boolean
    RaceDetailDto:
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        location:
          type: string
        date:
          type: string
          format: date
        description:
          type: string
        isPublic:
          type: boolean
    RaceDetailListDto:
      properties:
        races:
          type: array
          items:
            $ref: '#/components/schemas/RaceDetailDto'