dev:
  tempDir: "dev-tmp"

public-url: http://localhost:8080
tunel-url:

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/is-regatta
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: true
  flyway:
    enabled: true

server:
  servlet:
    session:
      persistent: true
      timeout: 3600
      store-dir: ${dev.tempDir}/server
  error:
    include-message: always
    include-binding-errors: always
    include-exception: true
    include-stacktrace: always