dev:
  tempDir: "dev-tmp"

public-url: http://localhost:8080
tunel-url: https://shiny-laws-jog.loca.lt

spring:
  datasource:
    url: #
    username: #
    password: #
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: true
  flyway:
    enabled: false

server:
  servlet:
    session:
      persistent: true
      timeout: 3600
      store-dir: ${dev.tempDir}/server
  error:
    include-message: always
    include-binding-errors: always
    include-exception: true
    include-stacktrace: always